### ISSUE TITLE
Compilation error icpc 14.0.3

### ISSUE THREAD

**Issue by mikeoconnor0308** [g-truc/glm#354]
Trying to compile on a unix system with icpc 14.0.3 (gcc version 4.8.1 compatibility).

Seems to dislike this line in setup.hpp

```c
#elif GLM_COMPILER & (GLM_COMPILER_LLVM | GLM_COMPILER_APPLE_CLANG | GLM_COMPILER_INTEL)
#	define GLM_HAS_CXX11_STL __has_include("__config")
```

```
$ icpc core_type_vec3.cpp
In file included from glm/detail/func_exponential.hpp(132),
                 from glm/detail/func_geometric.inl(33),
                 from glm/detail/func_geometric.hpp(142),
                 from glm/geometric.hpp(35),
                 from core_type_vec3.cpp(34):
glm/detail/func_exponential.inl(42): error: function call is not allowed in a constant expression
  #	if GLM_HAS_CXX11_STL
   	   ^

In file included from glm/detail/func_exponential.hpp(132),
                 from glm/detail/func_geometric.inl(33),
                 from glm/detail/func_geometric.hpp(142),
                 from glm/geometric.hpp(35),
                 from core_type_vec3.cpp(34):
glm/detail/func_exponential.inl(42): error: expression must have integral or enum type
  #	if GLM_HAS_CXX11_STL
   	   ^
.....
```

Any thoughts?

**Comment by Groovounet** [comment]
This issue is fixed in master branch for GLM 0.9.7 release.

Thanks,
Christophe
