### ISSUE TITLE
MSVC 2015U3 compile error in tvec4<T, P>::tvec4(ctor)

### ISSUE THREAD

**Issue by ma30002000** [g-truc/glm#555]
When updating GLM from 0.9.7.6 to 0.9.8.1, the following compile error occurs in MSVC 2015U3:
`c:\devel\videosdk\vcsmm\include\glm\detail\type_vec4.inl(182): error C2476: 'constexpr' constructor does not initialize all members
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(42): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::x' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(42): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::y' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(42): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::z' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(42): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::w' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(43): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::r' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(43): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::g' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(43): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::b' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(43): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::a' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(44): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::s' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(44): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::t' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(44): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::p' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(44): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::q' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(46): note: 'glm::tvec4<float,glm::aligned_lowp>::data' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail\type_vec4.inl(183): note: while compiling class template member function 'glm::tvec4<float,glm::aligned_lowp>::tvec4(glm::ctor)'
1>  c:\devel\videosdk\vcsmm\include\glm\detail\type_vec4_simd.inl(155): note: see reference to function template instantiation 'glm::tvec4<float,glm::aligned_lowp>::tvec4(glm::ctor)' being compiled
1>  c:\devel\videosdk\vcsmm\include\glm\detail\type_vec4_simd.inl(154): note: see reference to class template instantiation 'glm::tvec4<float,glm::aligned_lowp>' being compiled`

Adding a default ctor call for all element fixes the issue:
```
@@ -180,6 +180,7 @@
 
 	template <typename T, precision P>
 	GLM_FUNC_QUALIFIER GLM_CONSTEXPR_CTOR tvec4<T, P>::tvec4(ctor)
+		: x(), y(), z(), w() 
 	{}
 
 	template <typename T, precision P>

```

**Comment by rioharu** [comment]
You don't need to initialize all members, just one will suffice.

**Comment by Groovounet** [comment]
This issue should be fixed in GLM 0.9.8 and master branches.

Thanks for reporting,
Christophe

**Comment by ma30002000** [comment]
Unfortunately, this issue is still there - the referenced commit only fixes #555, but not this ticket.

**Comment by ma30002000** [comment]
Could you please reopen the issue?

**Comment by Groovounet** [comment]
Could you use #define GLM_FORCE_MESSAGES, build and copy paste the information GLM returns?
I couldn't repro.

Thanks,
Christophe

**Comment by ma30002000** [comment]
1>  GLM: Windows platform detected
1>  GLM: version 0.9.8.2
1>  GLM: Visual C++ compiler detected
1>  GLM: 64 bits model
1>  GLM: SSE2 instruction set
1>  GLM: C++11
1>  GLM: Swizzling operators disabled, #define GLM_SWIZZLE to enable swizzle operators
1>  GLM: Depth clip space: negative one to one
1>  GLM: Coordinate system: right handed
1>  GLM: .length() returns glm::length_t, a typedef of int following the GLSL specification
1>  GLM: Core library included
1>  GLM: GLM_GTC_constants extension included
1>  GLM: GLM_GTC_matrix_transform extension included
1>  GLM: GLM_GTX_transform extension included
1>  GLM: GLM_GTC_epsilon extension included
1>  GLM: GLM_GTC_quaternion extension included
1>  GLM: GLM_GTX_norm extension included
1>  GLM: GLM_GTX_quaternion extension included
1>  GLM: GLM_GTX_rotate_vector extension included
1>  GLM: GLM_GTX_vector_angle extension included
1>c:\devel\videosdk\vcsmm\include\glm\detail\type_vec4.inl(182): error C2476: 'constexpr' constructor does not initialize all members
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(42): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::x' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(42): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::y' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(42): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::z' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(42): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::w' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(43): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::r' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(43): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::g' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(43): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::b' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(43): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::a' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(44): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::s' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(44): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::t' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(44): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::p' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(44): note: 'glm::tvec4<float,glm::aligned_lowp>::<unnamed-tag>::q' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail/type_vec4.hpp(46): note: 'glm::tvec4<float,glm::aligned_lowp>::data' was not initialized by the constructor
1>  c:\devel\videosdk\vcsmm\include\glm\detail\type_vec4.inl(183): note: while compiling class template member function 'glm::tvec4<float,glm::aligned_lowp>::tvec4(glm::ctor)'
1>  c:\devel\videosdk\vcsmm\include\glm\detail\type_vec4_simd.inl(155): note: see reference to function template instantiation 'glm::tvec4<float,glm::aligned_lowp>::tvec4(glm::ctor)' being compiled
1>  c:\devel\videosdk\vcsmm\include\glm\detail\type_vec4_simd.inl(154): note: see reference to class template instantiation 'glm::tvec4<float,glm::aligned_lowp>' being compiled

**Comment by Groovounet** [comment]
Do you have a simple code sample to repro?

**Comment by Groovounet** [comment]
How do you get GLM: C++11? Visual C++ 2015 is not fully C++11 compatible and should return C++0x.

**Comment by Groovounet** [comment]
This issue should be fixed in GLM 0.9.8 and master branches. 

I think you are using GLM_FORCE_CXX11 in your code with Visual C++ however Visual C++ doesn't fully support C++11. 

By default GLM will automatically detect the compiler and its version to use only the feature set supported by the compiler. Using GLM_FORCE_CXX11, you override this system to use the C++11 features.

Thanks,
Christophe
