### ISSUE TITLE
Linker error for inverse() on version 0.9.5

### ISSUE THREAD

**Issue by wreardan** [g-truc/glm#147]
This is the offending line of code (viewMatrix is a mat4):
    mat3 normalMatrix = inverse(transpose(mat3(viewMatrix)));

Linker error message (Visual Studio 2012):

1>Object.obj : error LNK2019: unresolved external symbol "struct glm::detail::tmat3x3<float,0> __cdecl glm::detail::inverse<float,0>(struct glm::detail::tmat3x3<float,0> const &)" (??$inverse@M$0A@@detail@glm@@YA?AU?$tmat3x3@M$0A@@01@ABU201@@Z) referenced in function "public: virtual void __thiscall Object::Render(struct glm::detail::tmat4x4<float,0>,struct glm::detail::tmat4x4<float,0>,class Lights)" (?Render@Object@@UAEXU?$tmat4x4@M$0A@@detail@glm@@0VLights@@@Z)

This code works fine with version 0.9.4, am I doing something wrong here?

Thanks a lot for the great library!!
Wesley
