### ISSUE TITLE
Internal compiler error when targeting c++17 with the latest versions of gcc

### ISSUE THREAD

**Issue by robertoraggi** [g-truc/glm#754]
Hi,

There's an issue with the declarations of the constexpr constructors when targeting c++17 with gcc.

$ cat test.cpp 
#include "glm/mat3x3.hpp"

int main()
{
   glm::mat3 v(0);
}

$ g++ -xc++ -std=c++17 test.cpp 
test.cpp: In function ‘int main()’:
test.cpp:5:17: internal compiler error: in gimplify_expr, at gimplify.c:12200
    glm::mat3 v(0);

A possible workaround is to ensure that GLM_FORCE_CTOR_INIT is defined when targeting gcc/C++17, e.g.

$ g++ -std=c++17 -DGLM_FORCE_CTOR_INIT test.cpp

**Comment by Wunkolo** [comment]
I'm getting the very same error when trying to declare a matrix:
```
/tests/Scene1.cpp:47:50: internal compiler error: in gimplify_expr, at gimplify.c:12200
   glm::f32mat3 Transformation = glm::f32mat3(1.0f);
                                                  ^
```

Output of my `gcc -v`
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.3.1 20180312 (GCC)
```
Compiled using cmake with `set( CMAKE_CXX_STANDARD 14 )`. The global `GLM_FORCE_CTOR_INIT` processor definition seems to work for me as a temporary bypass for now.

**Comment by robertoraggi** [comment]
Also, related to this issue. A `constexpr` declaration of a matrix requires `GLM_FORCE_CTOR_INIT` to compile with gcc 7.3 and 8.x.

$ cat m.cpp 

```
#include <glm/glm.hpp>
int main() {
constexpr glm::mat3 m(1);
}
```

$ g++ -std=c++14 m.cpp -I .
```
m.cpp: In function ‘int main()’:
m.cpp:3:24: error: ‘glm::mat3{glm::mat<3, 3, float, (glm::qualifier)0>::col_type [3]{(void)0, (void)0, (void)0}}’ is not a constant expression
 constexpr glm::mat3 m(1);
```

This should compile fine
$ g++ -std=c++14 m.cpp -DGLM_FORCE_CTOR_INIT -I .

**Comment by DCubix** [comment]
I'm getting the same error on MinGW-w64 GCC 7.3 while trying to make a x64 build.
![](https://media.discordapp.net/attachments/103875996138102784/446402166459072513/unknown.png)

**Comment by xyproto** [comment]
I'm unable to reproduce the issue, it works fine here.

gcc 8.1.1
64-bit Arch Linux
glm 0.9.9.0

**Comment by Groovounet** [comment]
This issue should be fixed in master branch for GLM 0.9.9.1.
Let me know if this is not the case for you.

Thanks for contributing,
Christophe
