### ISSUE TITLE
master fails to compile with MSBuild 14

### ISSUE THREAD

**Issue by fgfuchs** [g-truc/glm#749]
When I try to compile, using MSBuild 14.0, I get 25 errors, similar to this one:

\glm\glm\detail/type_vec2.hpp(131): error C2610: 'glm::vec<2,T,Q> &glm::vec<2,T,Q>::operator =(const glm::vec<2,T,Q> &) const': is not a special member function which can be defaulted

This must have been introduced by a commit within the last week. It would be great if this could be fixed, so that it compiles again using windows. (the code still compiles using gcc 7.)

**Comment by fgfuchs** [comment]
I tried to switch to branch 0.9.8, which worked on windows with aforementioned compiler, but not with gcc 7.3.1. Then I get errors like:

/glm/glm/detail/type_vec4_simd.inl:156:11: error: ‘struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));

It would be great if master could be fixed asap :)

**Comment by urzq** [comment]
Same problem here !
Thanks for your nice library :)

**Comment by fgfuchs** [comment]
just FYI: branch 0.9.8 compiles with gcc 6.3 but not with 7.3

**Comment by Groovounet** [comment]
This issue was fixed by https://github.com/g-truc/glm/commit/5ba45d302cd409797a2a8ad0897cccd4bb492012

Thanks for contributing,
Christophe
